### ISSUE TITLE
attempt to re-open an already-closed object: SQLiteDatabase:

### ISSUE THREAD

**Issue by ingu88** [lapism/SearchBar-SearchView#178]
search error in test app v 3.6.3

try:
searching in main
go back to main page on result page
again try to search in main

sorry my bad english ㅠㅠ

**Comment by lapism** [comment]
I will try...If it will be a bug I will fix it in next version ASAP.

**Comment by lapism** [comment]
Hi, I was not able to reproduce that. Could you give more info?

**Comment by ingu88** [comment]
more info:
i think... maybe this problem is associated with Language.

Alphabet when there was no problem.
with korean.. search a problem.

**Comment by ingu88** [comment]
> java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/kr.go.naju.gov_phonebook/databases/search_history_database.db
                                                                              at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
                                                                              at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1413)
                                                                              at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1356)
                                                                              at com.lapism.searchview.SearchHistoryTable.getAllItems(**SearchHistoryTable.java:117**)
                                                                              at com.lapism.searchview.SearchAdapter$1.publishResults(SearchAdapter.java:115)
                                                                              at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:282)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

> 

SearchHistoryTable.java:117
logcat

**Comment by lapism** [comment]
I am not really sure because I do not speak korean. So if you would be able to fix it I will be very happy.

**Comment by lapism** [comment]
And dbHelper should not be closed.

**Comment by RJFares** [comment]
If you couldn't fix it, refer to my comment in #160

**Comment by sanu-soman** [comment]
Hi, To reproduce this error, type in a really long string in the search bar and then press and hold the backspace button to completely delete it, at this point the app crashes.

**Comment by lapism** [comment]
thanks for info
