### ISSUE TITLE
IllegalStateException : attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/[app-package]/databases/search_history_database.db

### ISSUE THREAD

**Issue by rgdev** [lapism/SearchBar-SearchView#188]
The following crash was caught by Crashlytics in my app : 

```
Fatal Exception: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/[app-package]/databases/search_history_database.db
   at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
   at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1312)
   at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
   at com.lapism.searchview.SearchHistoryTable.getAllItems(SearchHistoryTable.java:117)
   at com.lapism.searchview.SearchAdapter$1.publishResults(SearchAdapter.java:115)
   at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:282)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5417)
   at java.lang.reflect.Method.invoke(Method.java)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

The issue occured on Android 5 and 6 (non-rooted devices).

**Comment by lapism** [comment]
It will be fixed in 4.0.

**Comment by RJFares** [comment]
If you couldn't fix it, refer to my comment in #160

**Comment by gbirk** [comment]
I'm also seeing a lot of this bug on v4.0

**Comment by lapism** [comment]
Hi, I thought that was fixed already ...

**Comment by J-Yen** [comment]
I have the same bug sometimes. Is it a bug in the library or my implementation?

**Comment by J-Yen** [comment]
`W/Filter: An exception occured during performFiltering()!
          java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/jacobs.yen.watchtracker/databases/search_history_database.db
              at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
              at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
              at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1257)
              at com.lapism.searchview.SearchHistoryTable.getAllItems(SearchHistoryTable.java:116)
              at com.lapism.searchview.SearchAdapter$1.performFiltering(SearchAdapter.java:73)
              at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
              at android.os.Handler.dispatchMessage(Handler.java:102)
              at android.os.Looper.loop(Looper.java:154)
              at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by rgdev** [comment]
any update on this ?

**Comment by lapism** [comment]
ASAP

**Comment by fgnm** [comment]
I don't know if this could help now but I've fixed this problem. The bug is that you are instantiating the SearchHistoryTable two times, both in SearchAdapter and in BaseActivity. Removing one of these (preferably in SearchAdapter) everything works as expected.

**Comment by lapism** [comment]
Thanks. I till try it ASAP.

**Comment by PhilippeBoisney** [comment]
Same error here...

**Comment by gbirk** [comment]
Any updates on this?

**Comment by MinaSamirCap** [comment]
I get the same error but I use this version of library 
implementation 'com.lapism:searchview:5.0.0-alpha7'

I noticed that I get the crash after I enter the same word from keyboard but did not choose it from the list.,
after long search I can not understand why this happen .. but I solve the problem by check if the new word I get in the database or not .. if exist I will not add it if not I add it ..
like this 

searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {
                final String finalQuery = query.trim();
                if (!itemExist(finalQuery)) {
                    searchHistoryTable.addItem(new SearchItem(finalQuery));
                }
                searchView.close(false);
                // here write your code
                return true;
            }

            @Override
            public boolean onQueryTextChange(String newText) {
                return false;
            }
        });

//////////////////// itemExist function
private boolean itemExist(String finalQuery) {
        List<SearchItem> items = searchHistoryTable.getAllItems(null);
        for (SearchItem item : items) {
            if (item.getText().equals(finalQuery)) {
                return true;
            }
        }
        return false;
    }

hope my answer was helpful ...
