### ISSUE TITLE
Issue alpha4

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [lapism/SearchBar-SearchView#309]
`Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:569)
       at com.company.app.Fragments.Fragment.filter(Fragment.java:2290)
       at com.company.app.Fragments.Fragment$4.onQueryTextChange(Fragment.java:580)
       at com.lapism.searchview.SearchView.onTextChanged(SearchView.java:1099)
       at com.lapism.searchview.SearchView.access$000(SearchView.java:62)
       at com.lapism.searchview.SearchView$2.onTextChanged(SearchView.java:261)
       at android.widget.TextView.sendOnTextChanged(TextView.java:8273)
       at android.widget.TextView.handleTextChanged(TextView.java:8337)
       at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10344)
       at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:962)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:496)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:435)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:30)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:676)
       at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:435)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:333)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5319)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)`

In this line 2290 I have:
`            for (CustomList list: list2) {
`

I don't know if this bug is in the new alpha6 (I have to upload my app to PlayStore with this version).

How should I do this iteration to avoid this problem?

Filter method is used to allow the users write in SearchView to search items, the problem is appearing when the items change at the same time the user writes. I can't reproduce it in my phone.

![image](https://user-images.githubusercontent.com/7463564/30325662-e085f18e-97c5-11e7-811b-5ccc10361ddc.png)

**Comment by HusseinElFeky** [comment]
It is not a bug in the library. I believe you are calling something like `list2.remove(list);` under a certain condition. If that's the case, check this [link](https://stackoverflow.com/questions/223918/iterating-through-a-collection-avoiding-concurrentmodificationexception-when-re) on how to fix it.

**Comment by Dahnark** [comment]
This is the code @HusseinElFeky :

```
listFiltered.clear();
            for (CustomList list: list2) {
                if (list.getName().toLowerCase().startsWith(text.toLowerCase())) {
                    listFiltered.add(summoner);
                }
            }
            activity.runOnUiThread(() -> summonerAdapter.notifyDataSetChanged());
```

**Comment by HusseinElFeky** [comment]
@Dahnark I'm not sure what the problem is. Do you change anything regarding `list2` at any point? Can you also maybe try always calling `listFiltered.add(summoner);` by removing the condition and test if your app crashes?

**Comment by Dahnark** [comment]
The app is never crashing for me, I can't test it...

```
 public void filter(final String text) {
        if (TextUtils.isEmpty(text)) {
            listFiltered.clear();
            listFiltered.addAll(list2);
            activity.runOnUiThread(() -> adapter.notifyDataSetChanged());
        } else if (text.equals("All")) {
            listFiltered.clear();
            listFiltered.addAll(list2);
            activity.runOnUiThread(() -> adapter.notifyDataSetChanged());
        } else {
            listFiltered.clear();
            for (CustomList list: list2) {
                if (list.getName().toLowerCase().startsWith(text.toLowerCase())) {
                    listFiltered.add(list);
                }
            }
            activity.runOnUiThread(() -> adapter.notifyDataSetChanged());
        }
    }
```

**Comment by HusseinElFeky** [comment]
Weird, I don't see anything wrong. :/ Do you have any code in `onQueryTextChange()` other than `filter()`?

**Comment by Dahnark** [comment]
```
@Override
public boolean onQueryTextChange(String query) {
     filter(query);
     return true;
}
```

**Comment by boswelja** [comment]
why don't you use alpha6? I heard that was released

**Comment by HusseinElFeky** [comment]
@Dahnark I have no idea what's causing this issue. :/

**Comment by Dahnark** [comment]
I have to upload it to play store

**Comment by boswelja** [comment]
what does your CustomList class look like?

**Comment by boswelja** [comment]
@Dahnark whats wrong with using alpha6 in a public release if you're already using alpha4?

**Comment by Dahnark** [comment]
I said a lot of times, I have to upload the app with alpha6 to the play store but this bug maybe is in alpha6 because nobody report it before.

**Comment by boswelja** [comment]
@Dahnark oh so that's what you mean't, your use of have (present tense) over had (past tense) confused me, I thought you were going to upload this build but encountered this issue, my bad.. But as I said before, what does your CustomList class look like?

**Comment by Dahnark** [comment]
really my English is not very good :( when I arrive to home I will copy the class

**Comment by lapism** [comment]
I will take a look on this issue this weekend probably.

**Comment by Dahnark** [comment]
@boswelja 
```
public class MyClass {

    private String string1, string2, ..., stringN;
    private Boolean boolean1;

    Summoner(String string1, String string2, Boolean boolean1, String string3, ..., String stringN) {
        this.string1 = string1;
        this.string2 = string2;
        this.boolean1 = boolean1;
        this.string3 = string3;
        ...
        this.stringN = stringN;
    }

    autogenerate getter and setter for all.
}
```

**Comment by boswelja** [comment]
@Dahnark can't see anything wrong there either :/

**Comment by Dahnark** [comment]
well we should wait to @lapism check it

**Comment by Dahnark** [comment]
@lapism you will check this before upload beta1? About 150 crashes in the last 90 days.

And a little group of users had this problem but I think this is not a huge problem (9 crashes in last 90 days):

```
Fatal Exception: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
       at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
       at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
       at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
       at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:1032)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:972)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
       at com.lapism.searchview.SearchHistoryTable.getAllItems(SearchHistoryTable.java:111)
       at com.lapism.searchview.SearchAdapter$1.publishResults(SearchAdapter.java:137)
       at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:282)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5118)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
