### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by 1Kamal1** [lapism/SearchBar-SearchView#359]
Hi @lapism 
I would Like to Appreciate Your Work 
So First Thing which i want from you to Please Make a brief Description about how to use it , as most of the Beginners can't easily Understand
and anyhow i manage and started Working with your library there is an Exception Occurs 
Here is the Exception Details :

 E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.kamalverma.final_project/com.example.kamalverma.final_project.MainActivity}: android.view.InflateException: 
Binary XML file line #0: Binary XML file line #0: Error inflating class com.lapism.searchview.widget.SearchView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2825)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:203)
at android.app.ActivityThread.main(ActivityThread.java:6339)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.lapism.searchview.widget.SearchView
Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.lapism.searchview.widget.SearchView
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lapism.searchview.widget.SearchView" on path: DexPathList[[zip file "/data/app/com.example.kamalverma.final_project-1/base.apk", zip file "/data/app/com.example.kamalverma.final_project-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.kamalverma.final_project-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.kamalverma.final_project-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.kamalverma.final_project-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.kamalverma.final_project-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.kamalverma.final_project-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.kamalverma.final_project-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.kamalverma.final_project-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.kamalverma.final_project-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.kamalverma.final_project-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.kamalverma.final_project-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.kamalverma.final_project-1/lib/arm, /system/lib, /vendor/lib]]

at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at android.view.LayoutInflater.createView(LayoutInflater.java:609)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
at android.view.LayoutInflater.parseInclude(LayoutInflater.java:994)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:854)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
at android.support.v7.app.AppCompatDelegateImplV9.setContentView
(AppCompatDelegateImplV9.java:287)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
at com.example.kamalverma.final_project.MainActivity.onCreate(MainActivity.java:74)
03-25 00:35:13.460 24792-24792/com.example.kamalverma.final_project E/UncaughtException:
   at android.app.Activity.performCreate(Activity.java:6689)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2709)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2825)
  at android.app.ActivityThread.-wrap12(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
  at android.os.Handler.dispatchMessage(Handler.java:110)
  at android.os.Looper.loop(Looper.java:203)
  at android.app.ActivityThread.main(ActivityThread.java:6339)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

Sorry for the long Exception But i am new in android development and i have tried so many Libraries for Material Search View but none of them is working Perfectly 
Please Resolve this issue
Thanks

**Comment by lapism** [comment]
Hi. Please try last version from Bintray. But it works only from API 21+.
